name: Build and deploy Python app to Azure Web App - MSMAXPRO-Ai-Mentor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Login to Azure
        uses: azure/login@v2
        with:client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5D4E595C685B41F1879A35D14196D56A }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9765CFF29B2A4A1483CAB5F01A62B39B }}  
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F1757DBC5AF048F7839593EB50FBEA23 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MSMAXPRO-Ai-Mentor'
          slot-name: 'Production'
          startup-command: 'python bot.py'
          # We are deploying the source code directly, Azure will handle the build.
          package: .
